# Generated by Django 6.0.7 on 2026-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_no', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[('ist', 'ist semester'), ('2nd', '2nd semester'), ('3rd', '3rd semester'), ('4th', '4th semester'), ('5th', '5th Semester'), ('6th', '6th Semester'), ('7th', '7th Semester'), ('8th', '8th Semester')], max_length=10)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('exam_type', models.CharField(default='Regular', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
